version: "3.1"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        IMAGE_NAME: "dev:container-test-base"
    depends_on:
      - redis
    networks:
      - app-network
    ports:
      - "3000:9999"
    restart: always
    environment:
      REDIS_URL: redis://redis:6379/
      PORT: 9999

  redis:
    image: redis:3.2
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - app-network
    restart: always
    environment:
      REDIS_URL: redis://redis:6379/

networks:
  app-network:
